universe = vanilla
executable = hw4.sh
arguments = 3586.tgz cB58_Lyman_break.fit

output = hw4_1job.out
error = hw4_1job.err
log = hw4_1job.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz, packages_FITSio.tar.gz, hw4.R, /home/groups/STAT_DSCP/boss/cB58_Lyman_break.fit, /home/groups/STAT_DSCP/boss/tgz/3586.tgz

request_cpus = 1
request_memory = 2200MB
request_disk = 1GB 

queue 1
